### ISSUE TITLE
Auto-generating forms from ORM model declaration

### ISSUE THREAD

**Issue by ghost** [kohana/orm#109]
This can work just by (for example, of course):

```
echo ORM::factory('User')->renderForm();
```

And we see on screen all of fields, relations (selects (one-to-one), multiple checkboxes for many-to-many relations, etc.).

I saw that option in Symfony 1.4 (you declare model class and can render form for insert node to this moel). In Symfony 1.4 you can also generate the whole admin-panel by this options. But, of course, in Symfony 1.4 are Propel and Doctrine ORM conception...

So, i think, but it is the most important thing for framework. So, developers just declare model for table and use some automatic filters, rules, checks and form generating.

Also: need to think about automatic pagination generating for list of ORM data;

**Comment by dejwid** [comment]
There are modules to do sth like this.
Example: http://bmidget.github.io/kohana-formo/orm.html
Use vendor&composer or just kohana modules to add this to your website.
This issue should be closed.

**Comment by ghost** [comment]
Nope. That a bad solution. I know that.

I talk about conception level, not on: 'this needs to my admin panel'. On framework conception level.

**Comment by dejwid** [comment]
Why bad solution?
This is "extra" functionality and it should be installed by composer.
Kohana should be light framework so every extra functionality like this should be outside the main kohana package

**Comment by ghost** [comment]
Bad solution in code quality (i mean just this project), etc.

Okay, so, we should wait for response from Kohana developers about integration auto-generating forms by model declaration.

**Comment by enov** [comment]
@coll3ctor @dejwid kindly note that, unfortunately, I am not aware of any Kohana maintainer still relying heavily on Kohana ORM (this module). This is why support on this module is at lowest levels. I don't think there will be any integration for auto-generating forms through declaration of models. You might want to checkout other libraries for that.

**Comment by ghost** [comment]
@enov Thanks for response!

So, will wait for miracle and close that issue.
